#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRazorTemplates.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SimpleViewWithPartial.cshtml")]
    public partial class SimpleViewWithPartial : System.Web.Mvc.WebViewPage<TestRazorTemplates.Models.SimpleModel>
    {
        public SimpleViewWithPartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("In Main View: ");

            
            #line 3 "..\..\Views\SimpleViewWithPartial.cshtml"
         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\nBefore Partial\r\n");

            
            #line 5 "..\..\Views\SimpleViewWithPartial.cshtml"
Write(Html.Partial("SimplePartial", new { Name = "Partial" }));

            
            #line default
            #line hidden
WriteLiteral("\r\nAfter Partial");

        }
    }
}
#pragma warning restore 1591
