#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRazorTemplates.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ViewWithLink.cshtml"
    using TestRazorTemplates.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ViewWithLink.cshtml")]
    public partial class ViewWithLink : System.Web.Mvc.WebViewPage<TestRazorTemplates.Models.SimpleModel>
    {
        public ViewWithLink()
        {
        }
        public override void Execute()
        {
WriteLiteral("Name: ");

            
            #line 4 "..\..\Views\ViewWithLink.cshtml"
 Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 4 "..\..\Views\ViewWithLink.cshtml"
             Write(Url.Content("some content"));

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 4 "..\..\Views\ViewWithLink.cshtml"
                                           Write(Url.ContentAbsolute("~/images/logo.gif"));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
