#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDemoTemplates.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\HtmlLayout.cshtml"
    using EmailDemoTemplates.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/HtmlLayout.cshtml")]
    public partial class HtmlLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public HtmlLayout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xh" +
"tml1/DTD/xhtml1-strict.dtd\"> \n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\n<head>\n\t<meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral("/>\n\t<title>Your Message Subject or Title</title>\n\t<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\n\t\t/* Based on The MailChimp Reset INLINE: Yes. */  \n\t\t/* Client-specific Styles" +
" */\n\t\t#outlook a {padding:0;} /* Force Outlook to provide a \"view in browser\" me" +
"nu link. */\n\t\tbody{width:100% !important; -webkit-text-size-adjust:100%; -ms-tex" +
"t-size-adjust:100%; margin:0; padding:0;color:white} \n\t\t/* Prevent Webkit and Wi" +
"ndows Mobile platforms from changing default font sizes.*/ \n\t\t.ExternalClass {wi" +
"dth:100%;} /* Force Hotmail to display emails at full width */  \n\t\t.ExternalClas" +
"s, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td" +
", .ExternalClass div {line-height: 100%;}\n\t\t/* Forces Hotmail to display normal " +
"line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */ " +
"\n\t\t#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 10" +
"0% !important;background-color:black}\n\t\t/* End reset */\n\n\t\t/* Some sensible defa" +
"ults for images\n\t\tBring inline: Yes. */\n\t\timg {outline:none; text-decoration:non" +
"e; -ms-interpolation-mode: bicubic;} \n\t\ta img {border:none;} \n\t\t.image_fix {disp" +
"lay:block;}\n\n\t\t/* Yahoo paragraph fix\n\t\tBring inline: Yes. */\n\t\tp {margin: 1em 0" +
";}\n\n\t\t/* Hotmail header color reset\n\t\tBring inline: Yes. */\n\t\th1, h2, h3, h4, h5" +
", h6 {color: black !important;}\n\n\t\th1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: bl" +
"ue !important;}\n\n\t\th1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:act" +
"ive, h6 a:active {\n\t\tcolor: red !important; /* Preferably not the same color as " +
"the normal header link color.  There is limited support for psuedo classes in em" +
"ail clients, this was added just for good measure. */\n\t\t}\n\n\t\th1 a:visited, h2 a:" +
"visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {\n\t\tcolor: purp" +
"le !important; /* Preferably not the same color as the normal header link color." +
" There is limited support for psuedo classes in email clients, this was added ju" +
"st for good measure. */\n\t\t}\n\n\t\t/* Outlook 07, 10 Padding issue fix\n\t\tBring inlin" +
"e: No.*/\n\t\ttable td {border-collapse: collapse;}\n\n\t\t/* Remove spacing around Out" +
"look 07, 10 tables\n\t\tBring inline: Yes */\n\t\ttable { border-collapse:collapse; ms" +
"o-table-lspace:0pt; mso-table-rspace:0pt; }\n\n\t\t/* Styling your links has become " +
"much simpler with the new Yahoo.  In fact, it falls in line with the main credo " +
"of styling in email and make sure to bring your styles inline.  Your link colors" +
" will be uniform across clients when brought inline.\n\t\tBring inline: Yes. */\n\t\ta" +
" {color: orange;}\n\n\n\t\t/***************************************************\n\t\t***" +
"*************************************************\n\t\tMOBILE TARGETING\n\t\t*********" +
"*******************************************\n\t\t**********************************" +
"*****************/\n\t\t");

WriteLiteral(@"@media only screen and (max-device-width: 480px) {
			/* Part one of controlling phone number linking for mobile. */
			a[href^=""tel""], a[href^=""sms""] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^=""tel""], .mobile_link a[href^=""sms""] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}

		}

		/* More Specific Targeting */

		");

WriteLiteral(@"@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
		/* You guessed it, ipad (tablets, smaller screens, etc) */
			/* repeating for the ipad */
			a[href^=""tel""], a[href^=""sms""] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^=""tel""], .mobile_link a[href^=""sms""] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}
		}

		");

WriteLiteral("@media only screen and (-webkit-min-device-pixel-ratio: 2) {\n\t\t/* Put your iPhone" +
" 4g styles in here */ \n\t\t}\n\n\t\t/* Android targeting */\n\t\t");

WriteLiteral("@media only screen and (-webkit-device-pixel-ratio:.75){\n\t\t/* Put CSS for low den" +
"sity (ldpi) Android layouts in here */\n\t\t}\n\t\t");

WriteLiteral("@media only screen and (-webkit-device-pixel-ratio:1){\n\t\t/* Put CSS for medium de" +
"nsity (mdpi) Android layouts in here */\n\t\t}\n\t\t");

WriteLiteral("@media only screen and (-webkit-device-pixel-ratio:1.5){\n\t\t/* Put CSS for high de" +
"nsity (hdpi) Android layouts in here */\n\t\t}\n\t\t/* end Android targeting */\n\n\t</st" +
"yle>\n\n\t<!-- Targeting Windows Mobile -->\n\t<!--[if IEMobile 7]>\n\t<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
	
	</style>
	<![endif]-->   

	<!-- ***********************************************
	****************************************************
	END MOBILE TARGETING
	****************************************************
	************************************************ -->

	<!--[if gte mso 9]>
		<style>
		/* Target Outlook 2007 and 2010 */
		</style>
	<![endif]-->
</head>
<body>
<!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. -->
    <table");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" id=\"backgroundTable\"");

WriteLiteral(">\r\n        <tr>\r\n            <td>Header: My Funky Website!</td>\r\n        </tr>\n  " +
"      <tr>\n            <td");

WriteLiteral(" valign=\"top\"");

WriteLiteral("> \n");

WriteLiteral("                ");

            
            #line 145 "..\..\Views\Shared\HtmlLayout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n            </td>\n        </tr>\n        <tr>\r\n            <td><p>Footer: <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5636), Tuple.Create("\"", 5665)
            
            #line 149 "..\..\Views\Shared\HtmlLayout.cshtml"
, Tuple.Create(Tuple.Create("", 5643), Tuple.Create<System.Object, System.Int32>(Url.Absolute("~/tnc")
            
            #line default
            #line hidden
, 5643), false)
);

WriteLiteral(">terms and conditions</a> - <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5696), Tuple.Create("\"", 5733)
            
            #line 149 "..\..\Views\Shared\HtmlLayout.cshtml"
                , Tuple.Create(Tuple.Create("", 5703), Tuple.Create<System.Object, System.Int32>(Url.Absolute("~/unsubscribe")
            
            #line default
            #line hidden
, 5703), false)
);

WriteLiteral(">unsubscribe</a> - etc</p></td>\r\n        </tr>\n        <tr>\r\n            <td>Emai" +
"l HTML based on <a");

WriteLiteral(" href=\"http://htmlemailboilerplate.com\"");

WriteLiteral(" target =\"_blank\" style=\"color: orange; text-decoration: none;\">http://htmlemailb" +
"oilerplate.com</a>\n            </td>\r\n        </tr>\n    </table>  \n<!-- End of w" +
"rapper table -->\n</body>\n</html>\n");

        }
    }
}
#pragma warning restore 1591
