#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailDemoTemplates.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\PlainTextLayout.cshtml"
    using EmailDemoTemplates.Html;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/PlainTextLayout.cshtml")]
    public partial class PlainTextLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public PlainTextLayout()
        {
        }
        public override void Execute()
        {
WriteLiteral("Super Funky Website\r\n--------------------------------------\r\n");

            
            #line 4 "..\..\Views\Shared\PlainTextLayout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n--------------------------------------\r\nFooter:\r\nTerms and conditions: ");

            
            #line 7 "..\..\Views\Shared\PlainTextLayout.cshtml"
                 Write(Url.Absolute("~/tnc"));

            
            #line default
            #line hidden
WriteLiteral("\r\nUnsubscribe: ");

            
            #line 8 "..\..\Views\Shared\PlainTextLayout.cshtml"
        Write(Url.Absolute("~/unsubscribe"));

            
            #line default
            #line hidden
WriteLiteral("\r\nEmail sent on ");

            
            #line 9 "..\..\Views\Shared\PlainTextLayout.cshtml"
         Write(DateTime.Now.ToString());

            
            #line default
            #line hidden
WriteLiteral(" by Facepack\r\n");

        }
    }
}
#pragma warning restore 1591
